### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by greenyboy** [editorenhancer/features-and-bugs#1]
### Your Email Address

chris@greenyboy.plus.com

### What happened?

In the Padding/Margin area of the elements panel, if a padding value is set on the ID, then the purple vertical highlight line shows the style is applied to the ID but when you hover over the purple line, I don't see the "styled on ID" text slide in

### What did you expect to happen?

Would expect to see "Styled on ID" slide in

### Steps to reproduce the issue

Just add a value for any padding, save and ensure the value is now highlight with the vertical purple line. When you hover of this line, the text does not slide in

### Version of Editor Enhancer

5.0 beta

### Version of Oxygen

4.0.1

### List any other third-party Oxygen plugins or software you are using

Oxyninja, Litespeed cache, SEO Press, Forminator

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
No errors
```

### Code of Conduct

- [X] I agree

**Comment by editorenhancer** [comment]
It appears Oxygen by default does not show the slide-in on the Advanced > Size & Spacing tab. However, this led to realizing the little line was missing, so I fixed that at least. It is now first available in 5.0 release candidate 1, which is available as of today through your user dashboard. Link to change log: https://editorenhancer.com/editor-enhancer-5-0-release-candidate-rc-1/
